{% set name = "sacrebleu" %}
{% set version = "2.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d9e918147dc0777b2e159bff3246b8eb22d76f3b4ee3e6c6cbda05dc25dbb9c0
  patches:
    - no_changelog.patch

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - sacrebleu = sacrebleu.sacrebleu:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - typing
    - portalocker
    - regex
    - tabulate >=0.8.9
    - numpy >=1.17
    - colorama
    - lxml
    # extras_require={'ja': ['mecab-python3==1.0.3', 'ipadic>=1.0,<2.0']},

test:
  imports:
    - sacrebleu

about:
  home: https://github.com/mjpost/sacrebleu
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: Reference BLEU implementation that auto-downloads test sets and reports a version string to facilitate cross-lab comparisons

  description: |
    SacreBLEU (Post, 2018) provides hassle-free computation of shareable,
    comparable, and reproducible BLEU scores. Inspired by Rico Sennrich's
    multi-bleu-detok.perl, it produces the official WMT scores but works with
    plain text. It also knows all the standard test sets and handles
    downloading, processing, and tokenization for you.

extra:
  recipe-maintainers:
    - hmaarrfk
